name: Medikalam
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.10+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.6.0
  easy_rich_text: ^2.1.0
  equatable: ^2.0.5
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.3
  flutter_dotenv: ^5.1.0
  flutter_easyloading: ^3.0.5
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  get_it: ^7.7.0
  go_router: ^14.1.3
  image_picker: ^1.1.2
  image_picker_ios: ^0.8.12
  import_sorter: ^4.6.0
  injectable: ^2.4.4
  intl: ^0.20.2
  json_annotation: ^4.9.0
  location: ^8.0.0
  logger: ^2.3.0
  lottie: ^3.1.2
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  pretty_dio_logger: ^1.3.1
  provider: ^6.1.2
  reactive_forms: ^17.0.1
  responsive_sizer: ^3.3.1
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  sentry_flutter: ^8.14.0
  table_calendar: ^3.1.1
  toastification: ^2.2.0
  url_launcher: ^6.3.0
  url_launcher_ios: ^6.3.1
  very_good_analysis: ^5.1.0
  mobile_scanner: ^7.0.0
  audio_waveforms: ^1.3.0
dev_dependencies:
  build_runner: ^2.4.10
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

  freezed: ^2.5.2
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/animation/
    - assets/shapes/
    - assets/prescriptions/
    - .env.production
    - .env.development
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
